import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    alias(libs.plugins.droidkaigiPrimitiveKmp)
    alias(libs.plugins.droidkaigiPrimitiveKmpCompose)
    alias(libs.plugins.metro)
}

// Resolves the preview drawable directory that :core:preview:impl publishes on its
// "previewDrawables" consumable configuration, keeping this project out of impl's source layout.
val previewDrawablesScope by configurations.dependencyScope("previewDrawablesScope")
val previewDrawables by configurations.resolvable("previewDrawables") {
    extendsFrom(previewDrawablesScope)
}

dependencies {
    previewDrawablesScope(project(mapOf("path" to ":core:preview:impl", "configuration" to "previewDrawables")))
}

val generatePreviewImageEnum by tasks.registering {
    val drawableFiles = previewDrawables.asFileTree.matching { include("*.png") }
    val outDir = layout.buildDirectory.dir("generated/previewImage")
    inputs.files(drawableFiles).withPathSensitivity(org.gradle.api.tasks.PathSensitivity.NAME_ONLY)
    outputs.dir(outDir)
    doLast {
        val names = drawableFiles.map { it.nameWithoutExtension }.sorted()
        val pascal = { s: String -> s.split("_").joinToString("") { p -> p.replaceFirstChar { it.uppercaseChar() } } }
        val out = outDir.get().file("io/github/droidkaigi/confsched/core/preview/PreviewImage.kt").asFile
        out.parentFile.mkdirs()
        out.writeText(buildString {
            appendLine("// GENERATED by :core:preview:api generatePreviewImageEnum — do not edit.")
            appendLine("package io.github.droidkaigi.confsched.core.preview")
            appendLine()
            appendLine("// Type-safe handle per preview image; imageUrl is a preview:// sentinel that RemoteImage")
            appendLine("// resolves to the local drawable in preview / test builds.")
            appendLine("enum class PreviewImage(val imageUrl: String) {")
            names.forEach { appendLine("    ${pascal(it)}(\"preview://$it\"),") }
            appendLine("}")
        })
    }
}

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(generatePreviewImageEnum)
            dependencies {
                api(project(":core:model"))
                api(project(":core:designsystem"))
                api(libs.composeRuntime)
                api(libs.composeUi)
                api(libs.composeComponentsResources)
                api(libs.composeUiToolingPreview)
            }
        }
    }
}

tasks.withType<KotlinCompilationTask<*>>().configureEach {
    dependsOn(generatePreviewImageEnum)
}
